### PR TITLE
Influxdb udp-client usage added [fixed]

### PR DESCRIPTION
**Pull request by mguryanov**

### CODE REVIEW

**Comment by olegfedoseev** [comment]
You should update your master and resolve conflicts.

**Comment by mguryanov** [comment]
where from did you mean update my master?
you master or my udp-client?

**Comment by olegfedoseev** [comment]
You have a conflict because you try to merge with outdated master.
So, you should pull recent changes to master from upstream and update PR.

**Comment by mguryanov** [comment]
fixed

**Pull request merged**
